apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ui-deployment
spec:
  selector:
    matchLabels:
      app: wwwui
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wwwui
    spec:
      volumes:
      - name: data-volume
        hostPath: 
          path: /opt/bbk-app
          type: Directory   
      containers:
      - name: wwwui
        image: node
        volumeMounts:
        - name: data-volume
          mountPath: /data  
        #command: ["python", "-m", "SimpleHTTPServer"]
        command: 
        - /bin/sh
        - -c
        - |
          echo v1
          cd /data/bbk-apis/ui-angular/
          npm install
          npm run quick
        ports:
        - containerPort: 7626
---
kind: Service
apiVersion: v1
metadata:
  name: wwwui-service
spec:
  selector:
    app: wwwui
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 7626
  type: LoadBalancer
